# Generated by Django 3.2.22 on 2023-10-23 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='../default_profile_nu4k1e.jpg', help_text='Upload a profile picture', upload_to='profile_pics/'),
        ),
    ]
